language: go

os:
  - linux
  - osx

go:
  - 1.2.x
  - 1.3.x
  - 1.4
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
    exclude:
        - os: osx
          go: 1.2.x
        - os: osx
          go: 1.3.x
        - os: osx
          go: 1.4
        - os: osx
          go: 1.5.x
        - os: osx
          go: 1.6.x

before_install:
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then go get github.com/axw/gocov/gocov github.com/mattn/goveralls; fi

script:
  - go test -v -tags ci ./...
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then $GOPATH/bin/goveralls -service=travis-ci -ignore="examples/callbacks/callbacks.go,examples/dataloader/dataloader.go,examples/mycachedapp/mycachedapp.go"; fi

notifications:
  email:
    on_success: change
    on_failure: always
